galaxy_info:
  author: Alan Tai
  description: Generate Let's Encrypt SSL certificate
  license: MIT
  min_ansible_version: 2.4
  platforms:
    - name: Ubuntu
      versions:
        - bionic
  galaxy_tags:
    - letsencrypt
    - ssl
    - certificate
    - network
dependencies: []
